version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: tech_dojo
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3306
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    command: mysqld --upgrade=FORCE
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/init:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    depends_on:
      - "db"
    environment:
      DATABASE_URL: mysql://root:password@db:3306/tech_dojo
      ROCKET_ENV: staging
    ports:
      - "8000:8000"
    command: ./target/debug/ca-tech-dojo-rust
